version: "3.9"

services: 
  alvi-container:
    image: alvi-container:latest
    build: .
    container_name: alvi-container
    restart: always
    ports:
      - "1000:80"
    networks:
      - web-profile-net

networks:
  web-profile-net:
    driver: bridge
